# -*- mode: python ; coding: utf-8 -*-
# LETS 프로젝트 관리 시스템 — PyInstaller 빌드 설정

import os

block_cipher = None
base_dir = os.path.abspath('.')

a = Analysis(
    ['backend/main.py'],
    pathex=[
        os.path.join(base_dir, 'backend'),
    ],
    binaries=[],
    datas=[],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'fastapi.staticfiles',
        'fastapi.responses',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'starlette',
        'starlette.staticfiles',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'pydantic',
        'dotenv',
        'bcrypt',
        'requests',
        'bs4',
        'openpyxl',
        'apscheduler',
        'database',
        'config',
        'auth',
        'models',
        'collectors',
        'collectors.collect_all',
        'collectors.nara',
        'collectors.kstartup',
        'collectors.mss_biz',
        'collectors.ccei',
        'collectors.generic_scraper',
        'collectors.attachment_scraper',
        'collectors.base',
        'routers',
        'routers.auth',
        'routers.users',
        'routers.notices',
        'routers.tags',
        'routers.settings',
        'routers.keywords',
        'routers.sources',
        'routers.collection',
        'routers.organizations',
        'utils',
        'utils.db',
        'utils.text',
        'utils.dates',
        'utils.keywords',
        'utils.status',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='lets_server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
